version: "3"
services:
  credit-calc:
    build:
      context: .
      dockerfile: Dockerfile
    image: credit-calc-docker:latest
    container_name: credit-calc
    ports:
      - "3000:80"
    labels:
    - "traefik.http.routers.credit.rule=Host(`credit-calc.mp-malagora-photoprism.pl`)"
    - "traefik.http.routers.credit.tls=true"
    - "traefik.http.routers.credit.tls.certresolver=myresolver"
